// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkaJ0zeJKRdpiCgcM7F1upL4Ay-IBWTJQ',
    appId: '1:497395183084:web:ed1ff14ae4a5be1a1d24c9',
    messagingSenderId: '497395183084',
    projectId: 'respon2-902fb',
    authDomain: 'respon2-902fb.firebaseapp.com',
    storageBucket: 'respon2-902fb.appspot.com',
    measurementId: 'G-C9FD5E5ZHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtcZsxByWwporaNQ2-XNALvLV9tb1ha8',
    appId: '1:497395183084:android:1b63e8cb16cbf83f1d24c9',
    messagingSenderId: '497395183084',
    projectId: 'respon2-902fb',
    storageBucket: 'respon2-902fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6j0zA_z98TIndtjHhc8L6ZrUPN0Kt4g',
    appId: '1:497395183084:ios:ea2ba05a45abb36e1d24c9',
    messagingSenderId: '497395183084',
    projectId: 'respon2-902fb',
    storageBucket: 'respon2-902fb.appspot.com',
    iosBundleId: 'com.example.respon2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6j0zA_z98TIndtjHhc8L6ZrUPN0Kt4g',
    appId: '1:497395183084:ios:ea2ba05a45abb36e1d24c9',
    messagingSenderId: '497395183084',
    projectId: 'respon2-902fb',
    storageBucket: 'respon2-902fb.appspot.com',
    iosBundleId: 'com.example.respon2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkaJ0zeJKRdpiCgcM7F1upL4Ay-IBWTJQ',
    appId: '1:497395183084:web:e76cdd6fbf897b351d24c9',
    messagingSenderId: '497395183084',
    projectId: 'respon2-902fb',
    authDomain: 'respon2-902fb.firebaseapp.com',
    storageBucket: 'respon2-902fb.appspot.com',
    measurementId: 'G-JTE27LP4CX',
  );
}
